title: HEALTHY FOOD PORN
email: tommasp.rammella90@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Healthy food porn
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://yourdomain.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
source: ./frontend
